### ISSUE TITLE
Error in variable initialisation

### ISSUE THREAD

**Issue by gousiosg** [saltudelft/type4py#5]
When using the `preprocess` command with only the `-o` argument, the code crashes with the following

```
UnboundLocalError: local variable 'train_files_vars' referenced before assignment
```

This is because in the following extract

https://github.com/saltudelft/type4py/blob/93828c3d1a3460dc29cace398ca0dcb10ea14daf/type4py/preprocess.py#L302-L319

the `train_files_vars` variable is only initialised in the `if` branch

**Comment by mir-am** [comment]
Thank you @gousiosg for posting the issue. I have fixed the issue and pushed the fix to the main branch.

**Comment by gousiosg** [comment]
Thanks @mir-am, I can confirm that this works.
